### ISSUE TITLE
Update command run

### ISSUE THREAD

**Issue by annaparker** [russianvivi/bc2rome#1]
Kindly update (in the description) the command to correct one which opens/forward all needed ports.

Correct command is here: https://hub.docker.com/r/russianvivi/bc2rome

`sudo docker container run -p 19026:19026/tcp -p 19021:19021/tcp -p 19567:19567/udp -p 18390:18390/udp -p 5900:5900/tcp -p 80:80/tcp -p 48888:48888/tcp -v "./Instance:/project/R34_Full/Instance" russianvivi/bc2rome:latest`

**Comment by russianvivi** [comment]
Updated run command.
Thank you

**Comment by annaparker** [comment]
Seems not correctly, current one does not work:
`docker container run -p 19026:19026/tcp -p 19021:19021/tcp -p 19567:19567/udp -p 18390:18390/udp -p 5900:5900/tcp -p 80:80/tcp -p 48888:48888/tcp -v .\Instance\bc2rome/Instance:/project/R34_Full/Instance" russianvivi/bc2rome:latest``` `

It should be:
`docker container run -p 19026:19026/tcp -p 19021:19021/tcp -p 19567:19567/udp -p 18390:18390/udp -p 5900:5900/tcp -p 80:80/tcp -p 48888:48888/tcp -v "./Instance:/project/R34_Full/Instance" russianvivi/bc2rome:latest`

Also port 80 is not needed. I suggest to remove it.

PS. README syntax error. At _Open Startup.txt_ you gives command _nano ./Instance/ServerOptions.ini_
